### ISSUE TITLE
Add a 'What's This' to the age filter

### ISSUE THREAD

**Issue by stevenbertolucci** [senior-eng-project/Animal-Dating-App#65]
Having a question mark next to the age filter can inform users which age range fits in the category. Clicking on the question mark will display the age range for each category

**Comment by stevenbertolucci** [comment]
I was thinking of using 'newborn' to generalize animals that are kittens or puppies. It seems like a more broad term for young animals.

**Comment by cdgco** [comment]
I'm currently using this logic to define the youngest animals. `let baby = animal.type === "Cat" ? "Kitten" : animal.type === "Dog" ? "Puppy" : "Baby";`

**Comment by stevenbertolucci** [comment]
I can implement the 'What's This?' by including baby as an option to show users that the animal is less than 1 year old. Should I go ahead and implement this or should we stick with what we have for now in the database?

**Comment by TeresitaCGNader** [comment]
Do you mean you want to make "puppy" and "kitten" one label called "baby"? or add a new option called "baby"?

**Comment by cdgco** [comment]
I would prefer, where possible, that we show "kitten" or "puppy", such as in the animal's profile, but if that's not possible or you need a single value for something, "baby" should be fine. 

I think right now I'm actually storing the value "kitten" or "puppy" in the database, but if it's easier, I could just store "baby" for all animal types, then render it as "kitten" or puppy", so you don't have to deal with that logic, or can display it how you want, though it should still be possible to handle kitten, puppy, and baby on your components using logic similar to the code I posted above.

**Comment by stevenbertolucci** [comment]
I added a 'What's This?' (question mark with blue circle) to the Pets page along with explanations. Let me know what you think.
